sudo: false
language: cpp
os:
  - linux

compiler:
  - gcc

env:
  global:
    - ACE_ROOT=$TRAVIS_BUILD_DIR/ACE
    - MPC_ROOT=$TRAVIS_BUILD_DIR/MPC
    
before_install:
  - git clone --depth 1 git://github.com/DOCGroup/MPC.git
  
before_script:
  - export
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then echo -e "#include \"ace/config-linux.h\"" >> $ACE_ROOT/ace/config.h; fi
  - echo -e "workspace {\n" >> $TRAVIS_BUILD_DIR/travis.mwc
  - if [ "$ACE" == "1" ]; then echo -e "\$(ACE_ROOT)/ace/ace.mwc\n" >> $TRAVIS_BUILD_DIR/travis.mwc; fi 
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      if [ "$CXX" == "g++" ]; then
        echo -e "include \$(ACE_ROOT)/include/makeinclude/platform_linux.GNU" >> $ACE_ROOT/include/makeinclude/platform_macros.GNU;  
  
script:
  - perl $ACE_ROOT/bin/mwc.pl -type gnuace
  - make -j 6