sudo: false         # 开启基于容器的Travis CI任务，让编译效率更高。
language: cpp
os:
  - linux

compiler:
  - gcc

env:
  matrix:
    - ACE=1
  global:
    - CURPATH=$(pwd)
    - ACEDIR=$HOME/Tools
    - ACE_ROOT=$ACEDIR/ACE_wrappers
    - LD_LIBRARY_PATH=$ACE_ROOT/lib:$LD_LIBRARY_PATH
    - COMPILER=g++-7
    - secure: "TOG/oYZnuadPmIEt8aFele8MjktN4rOgL8Wgh9kj/LtwJs6Bh2rt9tcWgzBFbeZ/Heuxzm1bqNFoQ8wRriCgH1/tNCkC5oqSmQJtZvwYaa8k/UoarVtBYM6C9y831mf53+9nKh3yFUAIFF/jteEexnABqWSzImjaRNj2OFak9QAfFAbZ6ObVVQDmZdzISJcrmq3DeE0GAC5/JQWS56riqhdFhpgr4o/HZUICJgzNEeCZY7SI8F8XddHDB9PJ0/hGBhERvPIvGbzvzhpwWy3prrOlJAm7/3YbCwWPz46gu66UzEjgkpmXBMyf77w6XjRRAodr2KDyrIcegRs7pvnR8hkBpViy9Z/VJt+9K83oaf5m2JdnATlvysnTMqoYuG1oqpzTYjifMGLAAZrycIudnKoEqdsalHrhnhoz4CygcsCwxBJ+uO/EFA10RgNQctwQn/zJsG1ZfueECFOgRQ8EiB2yZdt519RvYWUS73qfQMVOavD90lFURpHm/JVJ1iwbbsrF6zmiql03S32LfWSYbPvrWl1GqP/l3P2EVadvG67slGwhKh7WJD/fUV0LugYa52WY8c5K0hAz9wV5teYDWS51ApmLMMk0DpaFbw6T7RoByuywF7i8vgORbKx+sn1e7PivpVhjKXbcOSv5yI1ZVPoRh7O11IkRkcVLkTVrNvU="


before_install:
  - mkdir -p $ACEDIR
  - cd $ACEDIR
  - wget http://download.dre.vanderbilt.edu/previous_versions/ACE-6.4.0.tar.gz
  - tar zxf ACE-6.4.0.tar.gz
  
before_script:
  - export
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then 
      echo -e "#include \"ace/config-linux.h\"" >> $ACE_ROOT/ace/config.h; 
      echo -e "#define ACE_HAS_EVENT_POLL" >> $ACE_ROOT/ace/config.h; 
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      if [ "$CXX" == "g++" ]; then
        echo -e "include \$(ACE_ROOT)/include/makeinclude/platform_linux.GNU" >> $ACE_ROOT/include/makeinclude/platform_macros.GNU;
      else
        echo -e "include \$(ACE_ROOT)/include/makeinclude/platform_linux_clang.GNU" >> $ACE_ROOT/include/makeinclude/platform_macros.GNU;
      fi
    fi

  - cd $ACE_ROOT
  - $ACE_ROOT/bin/mwc.pl -type gnuace ACE.mwc
  - make ACE > /dev/null 2>&1
  - ls $ACE_ROOT/lib/  
addons:
  coverity_scan:
    project:
      name: "liuchao412/TestTarvisACE"
      description: "Build submitted via Travis CI"
    notification_email: liuchao412@foxmail.com
    build_command_prepend: "cd $TRAVIS_BUILD_DIR;$ACE_ROOT/bin/mwc.pl -type gnuace"
    build_command:   "make -j 4"
    branch_pattern: master

script:
  - cd $TRAVIS_BUILD_DIR
  - $ACE_ROOT/bin/mwc.pl -type gnuace
  - make -j 6
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca- 
  
